/**********************************************************************

	--- Qt Architect generated file ---

	File: optionsdata.h
	Last generated: Sun Apr 26 23:24:19 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef OptionsData_included
#define OptionsData_included

#include <qdialog.h>
#include <qlined.h>

class OptionsData : public QDialog
{
    Q_OBJECT

public:

    OptionsData
    (
        QWidget *parent = NULL,
        const char *name = NULL
    );

    virtual ~OptionsData();

public slots:


protected slots:

    virtual void my_accept();

protected:
    QLineEdit *rec_thresh;
    QLineEdit *acc_sil_frames;
    QLineEdit *adj_win_width;
    QLineEdit *rej_thresh;
    QLineEdit *min_dist;

};

#endif // OptionsData_included
